<option selected="selected" value="destination">Destination</option>
<option value="AFGHANISTAN">Afghanistan</option>
<option value="ALBANIA">Albania</option>
<option value="ALGERIA">Algeria</option>
<option value="AMERICAN">American Samoa</option>
<option value="ANDORRA">Andorra</option>
<option value="ANGOLA">Angola</option>
<option value="ANGUILLA">Anguilla</option>
<option value="ANTIGUA">Antigua</option>
<option value="ARGENTINA">Argentina</option>
<option value="ARMENIA">Armenia</option>
<option value="ARUBA">Aruba</option>
<option value="AUSTRALIA">Australia</option>
<option value="AUSTRIA">Austria</option>
<option value="AZERBAIJAN">Azerbaijan</option>
<option value="BAHAMAS">Bahamas</option>
<option value="BAHRAIN">Bahrain</option>
<option value="BANGLADESH">Bangladesh</option>
<option value="BARBADOS">Barbados</option>
<option value="BELARUS">Belarus</option>
<option value="BELGIUM">Belgium</option>
<option value="BELIZE">Belize</option>
<option value="BENIN">Benin</option>
<option value="BERMUDA">Bermuda</option>
<option value="BHUTAN">Bhutan</option>
<option value="BOLIVIA">Bolivia</option>
<option value="BONAIRE">Bonaire</option>
<option value="BOSNIA AND HERZEGOVINA">Bosnia And Herzegovina</option>
<option value="BOTSWANA">Botswana</option>
<option value="BRAZIL">Brazil</option>
<option value="BRUNEI">Brunei</option>
<option value="BULGARIA">Bulgaria</option>
<option value="BURKINA FASO">Burkina Faso</option>
<option value="BURUNDI">Burundi</option>
<option value="CAMBODIA">Cambodia</option>
<option value="CAMEROON">Cameroon</option>
<option value="CANADA">Canada</option>
<option value="CANARY ISLAND">Canary Island</option>
<option value="CANARY ISLANDS, THE">Canary Islands, The</option>
<option value="CAPE VERDE">Cape Verde</option>
<option value="CAYMAN ISLANDS">Cayman Islands</option>
<option value="CENTRAL AFRICAN REPUBLIC">Central African Republic</option>
<option value="CHAD">Chad</option>
<option value="CHILE">Chile</option>
<option value="CHINA">China</option>
<option value="CHRISTMAS ISLAND">Christmas Island</option>
<option value="COCOS KEELING ISLANDS">Cocos Keeling Islands</option>
<option value="COLOMBIA">Colombia</option>
<option value="COMOROS">Comoros</option>
<option value="CONGO">Congo</option>
<option value="CONGO, THE DEMOCRATIC REPUBLIC">Congo, The Democratic Republic</option>
<option value="COOK ISLANDS">Cook Islands</option>
<option value="COSTA RICA">Costa Rica</option>
<option value="COTE D'IVOIRE">Cote D'ivoire</option>
<option value="CROATIA">Croatia</option>
<option value="CUBA">Cuba</option>
<option value="CURACAO">Curacao</option>
<option value="CYPRUS">Cyprus</option>
<option value="CZECH REPUBLIC">Czech Republic</option>
<option value="DAR ES SALAAM - TANZANIA">Dar Es Salaam - Tanzania</option>
<option value="DENMARK">Denmark</option>
<option value="DJIBOUTI">Djibouti</option>
<option value="DOMINICA">Dominica</option>
<option value="DOMINICAN REPUBLIC">Dominican Republic</option>
<option value="EAST TIMOR">East Timor</option>
<option value="ECUADOR">Ecuador</option>
<option value="EGYPT">Egypt</option>
<option value="EL SALVADOR">El Salvador</option>
<option value="EQUATORIAL GUINEA">Equatorial Guinea</option>
<option value="ERITREA">Eritrea</option>
<option value="ESTONIA">Estonia</option>
<option value="ETHIOPIA">Ethiopia</option>
<option value="FALKLAND ISLANDS">Falkland Islands</option>
<option value="FAROE ISLANDS">Faroe Islands</option>
<option value="FIJI">Fiji</option>
<option value="FINLAND">Finland</option>
<option value="FRANCE">France</option>
<option value="FRENCH GUYANA">French Guyana</option>
<option value="FRENCH POLYNESIA">French Polynesia</option>
<option value="GABON">Gabon</option>
<option value="GAMBIA">Gambia</option>
<option value="GEORGIA">Georgia</option>
<option value="GERMANY">Germany</option>
<option value="GHANA">Ghana</option>
<option value="GIBRALTAR">Gibraltar</option>
<option value="GREECE">Greece</option>
<option value="GREENLAND">Greenland</option>
<option value="GRENADA">Grenada</option>
<option value="GUADELOUPE">Guadeloupe</option>
<option value="GUAM">Guam</option>
<option value="GUATEMALA">Guatemala</option>
<option value="GUERNSEY">Guernsey</option>
<option value="GUINEA REPUBLIC">Guinea Republic</option>
<option value="GUINEA-BISSAU">Guinea-bissau</option>
<option value="GUYANA">Guyana</option>
<option value="HAITI">Haiti</option>
<option value="HONDURAS">Honduras</option>
<option value="HONG KONG">Hong Kong</option>
<option value="HUNGARY">Hungary</option>
<option value="ICELAND">Iceland</option>
<option value="INDIA">India</option>
<option value="INDONESIA">Indonesia</option>
<option value="IRAN (ISLAMIC REPUBLIC OF)">Iran (ISLAMIC REPUBLIC OF)</option>
<option value="IRAQ">Iraq</option>
<option value="ISRAEL">Israel</option>
<option value="ITALY">Italy</option>
<option value="JAMAICA">Jamaica</option>
<option value="JAPAN">Japan</option>
<option value="JERSEY">Jersey</option>
<option value="JORDAN">Jordan</option>
<option value="KAZAKHSTAN">Kazakhstan</option>
<option value="KENYA">Kenya</option>
<option value="KENYA - NAIROBI">Kenya - Nairobi</option>
<option value="KIRIBATI">Kiribati</option>
<option value="KOREA, REPUBLIC OF">Korea, Republic Of</option>
<option value="KOREA, THE D.P.R OF">Korea, The D.P.R Of</option>
<option value="KOSOVO">Kosovo</option>
<option value="KUWAIT">Kuwait</option>
<option value="KYRGYZSTAN">Kyrgyzstan</option>
<option value="LAOS">Laos</option>
<option value="LATVIA">Latvia</option>
<option value="LEBANON">Lebanon</option>
<option value="LESOTHO">Lesotho</option>
<option value="LIBERIA">Liberia</option>
<option value="LIBYA">Libya</option>
<option value="LIECHTENSTEIN">Liechtenstein</option>
<option value="LITHUANIA">Lithuania</option>
<option value="LUXEMBOURG">Luxembourg</option>
<option value="MACAU">Macau</option>
<option value="MACEDONIA">Macedonia</option>
<option value="MADAGASCAR">Madagascar</option>
<option value="MALAWI">Malawi</option>
<option value="MALAYSIA">Malaysia</option>
<option value="MALDIVES">Maldives</option>
<option value="MALI">Mali</option>
<option value="MALTA">Malta</option>
<option value="MAPUTO - MOZAMBIQUE">Maputo - Mozambique</option>
<option value="MARSHALL ISLANDS">Marshall Islands</option>
<option value="MARTINIQUE">Martinique</option>
<option value="MAURITANIA">Mauritania</option>
<option value="MAURITIUS">Mauritius</option>
<option value="MAYOTTE">Mayotte</option>
<option value="MEXICO">Mexico</option>
<option value="MICRONESIA">Micronesia</option>
<option value="MOLDOVA">Moldova</option>
<option value="MONACO">Monaco</option>
<option value="MONGOLIA">Mongolia</option>
<option value="MONTENEGRO, REPUBLIC OF">Montenegro, Republic Of</option>
<option value="MONTSERRAT">Montserrat</option>
<option value="MOROCCO">Morocco</option>
<option value="MOZAMBIQUE">Mozambique</option>
<option value="MYANMAR">Myanmar</option>
<option value="NAMIBIA">Namibia</option>
<option value="NAURU, REPUBLIC OF">Nauru, Republic Of</option>
<option value="NEPAL">Nepal</option>
<option value="NETHERLAND">Netherland</option>
<option value="NETHERLANDS ANTILLES">Netherlands Antilles</option>
<option value="NEVIS">Nevis</option>
<option value="NEW CALEDONIA">New Caledonia</option>
<option value="NEW YORK">New York</option>
<option value="NEW ZEALAND">New Zealand</option>
<option value="NICARAGUA">Nicaragua</option>
<option value="NIGER">Niger</option>
<option value="NIGERIA">Nigeria</option>
<option value="NIUE">Niue</option>
<option value="NORFOLK ISLAND">Norfolk Island</option>
<option value="NORTHERN IRELAND">Northern Ireland</option>
<option value="NORTHERN MARIANA ISLANDS">Northern Mariana Islands</option>
<option value="NORWAY">Norway</option>
<option value="OMAN">Oman</option>
<option value="PAKISTAN">Pakistan</option>
<option value="PALAU">Palau</option>
<option value="PALESTINE AUTHORITY">Palestine Authority</option>
<option value="PALESTINE AUTHORITY">Palestine Authority</option>
<option value="PALESTINIAN TERRITORY">Palestinian Territory</option>
<option value="PANAMA">Panama</option>
<option value="PAPUA NEW GUINEA">PAPUA NEW GUINEA</option>
<option value="PARAGUAY">Paraguay</option>
<option value="PERU">Peru</option>
<option value="PHILIPPINES">Philippines</option>
<option value="POLAND">Poland</option>
<option value="PORTUGAL">Portugal</option>
<option value="PUERTO RICO">PUERTO RICO</option>
<option value="PUERTO RICO - AGUADILLA">Puerto Rico - Aguadilla</option>
<option value="PUERTO RICO - ARECIBO">Puerto Rico - Arecibo</option>
<option value="PUERTO RICO - CAROLINA (FAJ)">Puerto Rico - Carolina (Faj)</option>
<option value="PUERTO RICO - CAROLINA (NRR)">Puerto Rico - Carolina (NRR)</option>
<option value="PUERTO RICO - GUAYNABO">Puerto Rico - Guaynabo</option>
<option value="PUERTO RICO - PONCE">Puerto Rico - Ponce</option>
<option value="PUERTO RICO - SAN JUAN">Puerto Rico - San Juan</option>
<option value="QATAR">Qatar</option>
<option value="REUNION ISLAND">Reunion Island</option>
<option value="ROMANIA">Romania</option>
<option value="RUSSIA">Russia</option>
<option value="RWANDA">Rwanda</option>
<option value="SAINT LUCIA">Saint Lucia</option>
<option value="SAINT MARTIN">Saint Martin</option>
<option value="SAINT PIERRE AND MIQUELON">Saint Pierre And Miquelon</option>
<option value="SAIPAN">Saipan</option>
<option value="SAMOA">Samoa</option>
<option value="SAN MARINO">San Marino</option>
<option value="SAO TOME AND PRINCIPE">Sao Tome And Principe</option>
<option value="SAUDI ARABIA">Saudi Arabia</option>
<option value="SCOTLAND">Scotland</option>
<option value="SENEGAL">Senegal</option>
<option value="SERBIA">Serbia</option>
<option value="SEYCHELLES">Seychelles</option>
<option value="SIERRA LEONE">Sierra Leone</option>
<option value="SINGAPORE">Singapore</option>
<option value="SLOVAKIA">Slovakia</option>
<option value="SLOVENIA">Slovenia</option>
<option value="SOLOMON ISLANDS">Solomon Islands</option>
<option value="SOMALIA">Somalia</option>
<option value="SOMALILAND, REPUBLIC OF">Somaliland, Republic Of</option>
<option value="SOUTH AFRICA">South Africa</option>
<option value="SOUTH SUDAN">South Sudan</option>
<option value="SPAIN">Spain</option>
<option value="SRILANKA">Srilanka</option>
<option value="ST KITTS &amp; NEVIS">St Kitts &amp; Nevis</option>
<option value="ST MAARTEN">St Maarten</option>
<option value="ST MARTIN">St Martin</option>
<option value="ST. BARTHELEMY">St. Barthelemy</option>
<option value="ST. EUSTATIUS">St. Eustatius</option>
<option value="ST. HELENA<">St. Helena</option>
<option value="ST. MAARTEN">St. Maarten</option>
<option value="ST. VINCENT">St. VincentSudan</option>
<option value="SUDAN">Sudan</option>
<option value="SURINAME">Suriname</option>
<option value="SWAZILAND">Swaziland</option>
<option value="SWEDEN">Sweden</option>
<option value="SWITZERLAND">Switzerland</option>
<option value="SYRIA">Syria</option>
<option value="TAHITI">Tahiti</option>
<option value="TAIPEI - TAIWAN">Taipei - Taiwan</option>
<option value="TAIWAN">Taiwan</option>
<option value="TAJIKISTAN">Tajikistan</option>
<option value="TANZANIA">Tanzania</option>
<option value="TTHAILANDH">Thailand</option>
<option value="TOGO">Togo</option>
<option value="TONGA">Tonga</option>
<option value="TRINIDAD AND TOBAGO">Trinidad And Tobago</option>
<option value="TUNISIA">Tunisia</option>
<option value="TURKEY">Turkey</option>
<option value="TURKMENISTAN">Turkmenistan</option>
<option value="TURKS AND CAICOS ISLANDS">Turks And Caicos Islands</option>
<option value="TUVALU">Tuvalu</option>
<option value="UGANDA">Uganda</option>
<option value="UKRAINE">Ukraine</option>
<option value="UNITED ARAB EMIRATES">United Arab Emirates</option>
<option value="UNITED KINGDOM">United Kingdom</option>
<option value="UNITED STATES OF AMERICA">United States Of America</option>
<option value="URUGUAY">Uruguay</option>
<option value="US">US</option>
<option value="UZBEKISTAN">Uzbekistan</option>
<option value="VANUATU">Vanuatu</option>
<option value="VATICAN CITY">Vatican City</option>
<option value="VENEZUELA">Venezuela</option>
<option value="VIETNAM">Vietnam</option>
<option value="VIRGIN ISLANDS (BRITISH)">Virgin Islands (British)</option>
<option value="VIRGIN ISLANDS (US)">Virgin Islands (US)</option>
<option value="WALLIS &amp; FUTUNA">Wallis &amp; Futuna</option>
<option value="WESTERN SAMAO">Western Samao</option>
<option value="YEMEN">Yemen</option>
<option value="ZAMBIA">Zambia</option>
<option value="ZAMBIA - LUSAKA">Zambia - Lusaka</option>
<option value="ZAMBIA - OTHERS">Zambia - Others</option>
<option value="ZIMBABWE">Zimbabwe</option>
<option value="IRELAND">Ireland</option>
</select>
